### ISSUE TITLE
give right to voters when the new address comes in 

### ISSUE THREAD

**Issue by EnbangWu** [EnbangWu/BoostVote#2]
Currently, we have a public address chairperson who can assign the right to voters, however, this is inconvenient because each transaction will cost the gas fees. 

**TODO**
- [ ] assign the rights to voters without a function. Since if we create a function then it needs a msg.sender and the chairperson is required.
- [ ] delete the giveRightToVote function and chairperson.
- [ ] write some unit tests to make sure that new addresses do have right to vote
